import * as React from "react";
import Head from "next/head";
import dynamic from "next/dynamic";

import styles from "../styles/Home.module.css";

// TODO: Resolve types definition for dynamic import
// @ts-ignore
const App1 = dynamic(() => import("app1/app1"), { suspense: true });

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <React.Suspense fallback="Loading App1">
          <App1 />
        </React.Suspense>
      </main>
    </div>
  );
}

Home.getInitialProps = async () => {
  return {};
};

export default Home;
